<!DOCTYPE html>
<html lang="ja">
<head>
	<base href="[+baseurl+]" />
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>GettinGPS - TOOLS</title>

<!-- Bootstrap core CSS -->
	<link href="[+templateurl+]/../_bootstrap/3.2.0/docs/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap theme -->
	<link href="[+templateurl+]/../_bootstrap/3.2.0/docs/dist/css/bootstrap-theme.min.css" rel="stylesheet">

<!-- Custom styles for this template --><!-- tmpvar: documentCssName -->
	<link href="[+templateurl+]/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">
	<link href="[+templateurl+]/sticky-footer-navbar/favicon.ico" rel="icon">

<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="[+templateurl+]/../_bootstrap/3.2.0/docs/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
	<script src="[+templateurl+]/../_bootstrap/3.2.0/docs/assets/js/ie-emulation-modes-warning.js"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<script src="[+templateurl+]/../_bootstrap/3.2.0/docs/assets/js/ie10-viewport-bug-workaround.js"></script>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</head>

<body role="document">
	<div class="text-center">
		GettinGPS<br>
		<br>
		<input id="radio1" type="radio" name="users" value="HG" />HG |
		<input id="radio2" type="radio" name="users" value="NG" />NG |
		<input id="radio3" type="radio" name="users" value="ME" checked />ME<br>
		<br>
		<button id="btnexec" class="btn btn-default" value="0">EXEC</button>
		<span id="isexecmsg">OFF</span> <span id="watchid" value=""></span><br>
	</div>
	<div id="pos" class="text-center">
	</div>
</body>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
<script src="[+templateurl+]/../_bootstrap/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
<script src="[+templateurl+]/../_bootstrap/3.2.0/docs/dist/js/bootstrap.min.js"></script>
<script src="[+templateurl+]/../_bootstrap/3.2.0/docs/assets/js/docs.min.js"></script>

<!-- tools -->
<!-- <script type="text/javascript" src="js/ajaxsample.js" ></script> -->
<script type="text/javascript" src="js/ajaxexecute.js" ></script>
<script type="text/javascript" src="js/getgps.js" ></script>

</html>
